blueprint: 1.0.0
name: Radio Edge Cloud
version: 1.0.0
description: This Blueprint defines an instance of the Radio Edge Cloud (from the
  Telco Appliance family of blueprints).
yaml:
  # Required hardware profiles (can match on either UUID or name)
  # Note: UUIDs would likely require a global registry of HW profiles.
  hardware_profile:
    or:
      - { uuid: 8a17384a-71d4-11e9-9e4c-0017f20fe1b8 }
      - { uuid: 9897a008-71d4-11e9-8bda-0017f20dbff8 }
      - { uuid: a4b4a570-71d4-11e9-adc2-0017f208759e }
  workflow:
    # Workflow that is invoked when the POD is created
    create:
      url: 'http://www.example.org/blueprints/REC/REC_create.py'
      components:
        # This script is used to generate self-signed certs for the remote-installer
        - 'http://www.example.org/blueprints/REC/gencerts.sh'
      input_schema:
        iso_primary: { type: string }
        iso_secondary: { type: string }
        input_yaml: { type: string }
        rc_host: { type: string }
